SELECT p.RECIPE_ID, m.COMPANY, p.WARE AS PRODUCT,
 group_concat(mat.WARE) AS MATERIAL FROM PRODUCT p

JOIN MANUFACTURER m ON m.RECIPE_ID = p.RECIPE_ID 
LEFT JOIN MATERIAL mat ON mat.RECIPE_ID = p.RECIPE_ID

GROUP BY p.RECIPE_ID
ORDER BY m.COMPANY