SELECT P.WARE, group_concat(DISTINCT M.WARE), SUBS.RES AS SUBPRODUCTS
FROM PRODUCT P
LEFT JOIN MATERIAL M ON M.RECIPE_ID = P.RECIPE_ID
LEFT JOIN (SELECT P1.WARE, group_concat(DISTINCT P2.WARE) AS RES, P1.RECIPE_ID
		FROM PRODUCT P1
		JOIN PRODUCT P2 ON P1.RECIPE_ID = P2.RECIPE_ID
		WHERE P1.WARE <> P2.WARE
		GROUP BY P1.WARE) SUBS ON SUBS.WARE = P.WARE
GROUP BY P.WARE