SELECT CMPS, PRODUCTS, CNT
FROM (SELECT COMPANY AS CMPS, group_concat(distinct WARE) AS PRODUCTS,count(DISTINCT WARE) AS CNT
		FROM MANUFACTURER M, PRODUCT P
		WHERE M.RECIPE_ID = P.RECIPE_ID
		GROUP BY COMPANY)
WHERE CNT = (SELECT count(DISTINCT WARE) AS CNT
		FROM MANUFACTURER M, PRODUCT P
		WHERE M.RECIPE_ID = P.RECIPE_ID
		GROUP BY COMPANY
		ORDER BY CNT DESC
		LIMIT 1)
ORDER BY CMPS