SELECT DISTINCT PRODUCT.WARE FROM MATERIAL, CATEGORY, PRODUCT
WHERE CATEGORY.CLASS LIKE "MINERAL" AND MATERIAL.WARE = CATEGORY.WARE
	AND PRODUCT.RECIPE_ID = MATERIAL.RECIPE_ID
ORDER BY PRODUCT.WARE ASC