SELECT DISTINCT MANUFACTURER.COMPANY FROM CATEGORY, PRODUCT, MANUFACTURER
WHERE CATEGORY.CLASS LIKE "FUEL" AND CATEGORY.WARE = PRODUCT.WARE 
	AND PRODUCT.RECIPE_ID = MANUFACTURER.RECIPE_ID
INTERSECT
SELECT DISTINCT MANUFACTURER.COMPANY FROM CATEGORY, PRODUCT, MANUFACTURER
WHERE CATEGORY.CLASS LIKE "FOOD" AND CATEGORY.WARE = PRODUCT.WARE 
	AND PRODUCT.RECIPE_ID = MANUFACTURER.RECIPE_ID