SELECT DISTINCT m.COMPANY, p.WARE, p2.WARE

FROM MANUFACTURER m
JOIN PRODUCT p ON p.RECIPE_ID = m.RECIPE_ID
JOIN CATEGORY c ON c.WARE = p.WARE AND c.CLASS LIKE "FOOD"

JOIN MANUFACTURER m2 ON m.COMPANY = m2.COMPANY
JOIN PRODUCT p2 ON p2.RECIPE_ID = m2.RECIPE_ID
JOIN CATEGORY c2 ON c2.WARE = p2.WARE AND c2.CLASS LIKE "FUEL"

ORDER BY m.COMPANY ASC