SELECT DISTINCT p.WARE
FROM PRODUCT p

EXCEPT

SELECT DISTINCT p.WARE
FROM PRODUCT p
JOIN MATERIAL m ON m.RECIPE_ID = p.RECIPE_ID
JOIN CATEGORY c ON m.WARE = c.WARE
WHERE c.CLASS NOT LIKE "MINERAL"

ORDER BY p.WARE ASC