SELECT DISTINCT m1.COMPANY
FROM MANUFACTURER m1

JOIN MATERIAL mat ON m1.RECIPE_ID = mat.RECIPE_ID
JOIN PRODUCT p ON p.WARE = mat.WARE

JOIN MANUFACTURER m2 ON m1.COMPANY = m2.COMPANY
WHERE m2.RECIPE_ID = p.RECIPE_ID

ORDER BY m1.COMPANY ASC