SELECT DISTINCT MANUFACTURER.COMPANY, PRODUCT.WARE FROM PRODUCT, CATEGORY, MANUFACTURER
WHERE CLASS like "RAW FOOD" AND PRODUCT.WARE = CATEGORY.WARE 
	AND PRODUCT.RECIPE_ID = MANUFACTURER.RECIPE_ID
ORDER BY PRODUCT.WARE, MANUFACTURER.COMPANY ASC