SELECT DISTINCT MANUFACTURER.COMPANY, PRODUCT.WARE
FROM MANUFACTURER, PRODUCT, CATEGORY

WHERE MANUFACTURER.COMPANY IN (
SELECT DISTINCT MANUFACTURER.COMPANY
FROM CATEGORY, PRODUCT, MANUFACTURER
WHERE CATEGORY.CLASS LIKE "FUEL" AND CATEGORY.WARE = PRODUCT.WARE
	AND PRODUCT.RECIPE_ID = MANUFACTURER.RECIPE_ID)

AND MANUFACTURER.COMPANY IN (
SELECT DISTINCT MANUFACTURER.COMPANY
FROM CATEGORY, PRODUCT, MANUFACTURER
WHERE CATEGORY.CLASS LIKE "FOOD" AND CATEGORY.WARE = PRODUCT.WARE
	AND PRODUCT.RECIPE_ID = MANUFACTURER.RECIPE_ID)
	
AND CATEGORY.CLASS LIKE "F%" AND CATEGORY.WARE = PRODUCT.WARE
AND PRODUCT.RECIPE_ID = MANUFACTURER.RECIPE_ID

ORDER BY MANUFACTURER.COMPANY