SELECT DISTINCT m1.COMPANY, mt2.WARE, p2.WARE, p1.WARE
FROM MANUFACTURER m1
JOIN PRODUCT p1 ON p1.RECIPE_ID = m1.RECIPE_ID
JOIN MATERIAL mt1 ON mt1.RECIPE_ID = m1.RECIPE_ID

JOIN MANUFACTURER m2 ON m2.COMPANY = m1.COMPANY
JOIN PRODUCT p2 ON p2.RECIPE_ID = m2.RECIPE_ID
LEFT JOIN MATERIAL mt2 ON mt2.RECIPE_ID = p2.RECIPE_ID
WHERE mt1.WARE = P2.WARE

ORDER BY m1.COMPANY, p2.WARE