SELECT m1.COMPANY, 
group_concat(DISTINCT mat1.WARE), mat1.RECIPE_ID,
group_concat(DISTINCT p1.WARE), mat2.RECIPE_ID, 
group_concat(DISTINCT p2.WARE)
FROM MANUFACTURER m1
JOIN MATERIAL mat1 ON mat1.RECIPE_ID = m1.RECIPE_ID
JOIN PRODUCT p1 ON p1.RECIPE_ID = mat1.RECIPE_ID

JOIN MANUFACTURER m2 ON m2.COMPANY = m1.COMPANY
JOIN MATERIAL mat2 ON p1.WARE = mat2.WARE 
	AND mat2.RECIPE_ID = m2.RECIPE_ID
JOIN PRODUCT p2 ON p2.RECIPE_ID = mat2.RECIPE_ID

GROUP BY m1.COMPANY, mat1.RECIPE_ID, mat2.RECIPE_ID