SELECT COMPANY FROM MANUFACTURER m
JOIN PRODUCT p ON p.RECIPE_ID = m.RECIPE_ID
JOIN CATEGORY c ON c.WARE = p.WARE
	AND C.CLASS LIKE "FOOD"
INTERSECT
SELECT COMPANY FROM MANUFACTURER m
JOIN PRODUCT p ON p.RECIPE_ID = m.RECIPE_ID
JOIN CATEGORY c ON c.WARE = p.WARE
	AND C.CLASS LIKE "FUEL"
INTERSECT
SELECT COMPANY FROM MANUFACTURER m
JOIN PRODUCT p ON p.RECIPE_ID = m.RECIPE_ID
JOIN CATEGORY c ON c.WARE = p.WARE
	AND C.CLASS LIKE "MINERAL"