SELECT COMPANY, group_concat(DISTINCT p.WARE) AS PRODUCTS, 
group_concat(DISTINCT mat.WARE) AS MATERIALS FROM MANUFACTURER m
LEFT JOIN MATERIAL mat ON mat.RECIPE_ID = m.RECIPE_ID
JOIN PRODUCT p ON p.RECIPE_ID = m.RECIPE_ID
GROUP BY COMPANY
