SELECT DISTINCT COMPANY
FROM MANUFACTURER 
WHERE COMPANY NOT IN
	(SELECT C.COMPANY
	FROM PRODUCT P, (SELECT avg(PRICE) AS PR, WARE FROM PRODUCT GROUP BY WARE) B
	JOIN MANUFACTURER C ON C.RECIPE_ID = P.RECIPE_ID
	WHERE P.PRICE <= PR * 1.2
	AND B.WARE = P.WARE)