SELECT COMPANY, CLASS, group_concat(DISTINCT P.WARE) AS wares
FROM MANUFACTURER M, CATEGORY C, PRODUCT P
WHERE M.RECIPE_ID = P.RECIPE_ID
AND P.WARE = C.WARE
AND NOT EXISTS (
    SELECT 1
    FROM CATEGORY SUB_C
    WHERE SUB_C.CLASS = C.CLASS
    AND NOT EXISTS (
        SELECT 1
        FROM PRODUCT P2, MANUFACTURER M2
        WHERE P2.RECIPE_ID = M2.RECIPE_ID
        AND P2.WARE = SUB_C.WARE
        AND M2.COMPANY = M.COMPANY
    )
)
GROUP BY COMPANY, CLASS